/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.dbus 3.1.12.v201801251438.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#include <v1/commonapi/examples/E02Attributes.hpp>
#include <v1/commonapi/examples/E02AttributesDBusStubAdapter.hpp>

namespace v1 {
namespace commonapi {
namespace examples {

std::shared_ptr<CommonAPI::DBus::DBusStubAdapter> createE02AttributesDBusStubAdapter(
                   const CommonAPI::DBus::DBusAddress &_address,
                   const std::shared_ptr<CommonAPI::DBus::DBusProxyConnection> &_connection,
                   const std::shared_ptr<CommonAPI::StubBase> &_stub) {
    return std::make_shared< E02AttributesDBusStubAdapter<::v1::commonapi::examples::E02AttributesStub>>(_address, _connection, std::dynamic_pointer_cast<::v1::commonapi::examples::E02AttributesStub>(_stub));
}

void initializeE02AttributesDBusStubAdapter() {
    CommonAPI::DBus::Factory::get()->registerStubAdapterCreateMethod(
        E02Attributes::getInterface(), &createE02AttributesDBusStubAdapter);
}

INITIALIZER(registerE02AttributesDBusStubAdapter) {
    CommonAPI::DBus::Factory::get()->registerInterface(initializeE02AttributesDBusStubAdapter);
}

} // namespace examples
} // namespace commonapi
} // namespace v1
